### PR TITLE
Resync sim and compiler

### PR DESCRIPTION
**Pull request by jessberg**
The main changes I made were to change how the filter is imported.  Now, the filter exists by itself in its own library with its own Cargo.toml and src folder, etc.  Because both the filter and the simulator use the rpc object, that was refactored into its own library as well.  In addition, I included the my_filter folder, which is an example of the kind of filter that the compiler should now make for the simulator.

### CODE REVIEW

**Review by anirudhSK — APPROVED** [review]

**Comment by anirudhSK** [comment]
This is quite a giant PR for me to look at. For now, I have approved this one. Going forward, let's break a PR up into smaller PRs where possible for ease of reviewing.

**Comment by fruffy** [comment]
The target folder should probably be put into the .gitignore.

**Comment by jessberg** [comment]
> The target folder should probably be put into the .gitignore.

I can't, because the simulator relies on the compiled versions of the libraries as inputs, and then the tests fail.  I changed it to only add the one compiled binary per library though, and that should cut down on the mess.

**Comment by jessberg** [comment]
> This is quite a giant PR for me to look at. For now, I have approved this one. Going forward, let's break a PR up into smaller PRs where possible for ease of reviewing.

Will do.

**Pull request closed without merging**
