### PR TITLE
Added headers to rpc

### LINKED ISSUE #13: Add custom headers
We should add the ability for filters to put in custom headers to an RPC, since this is how we can express different properties of nodes on a trace graph.

### PR DESCRIPTION
**Pull request by jessberg**
Adding headers to rpcs;  these will be used by the filters.  This closes the issue about having custom headers.

### CODE REVIEW

**Comment by fruffy** [comment]
Hmm this is kind of a weird abstraction. Technically, HTTP requests should be a class of their own. These are HTTP headers unrelated to RPC calls. But I guess for the purpose of this project it is fine? I am not sure how close we will get to the real thing with this.

**Comment by jessberg** [comment]
> Hmm this is kind of a weird abstraction. Technically, HTTP requests should be a class of their own. These are HTTP headers unrelated to RPC calls. But I guess for the purpose of this project it is fine? I am not sure how close we will get to the real thing with this.

Yes, I agree that it seems a little weird to lump them together.  However, I don't think we are going to be modeling anything lower-level than the RPCs, and since the proxy-wasm-sdks have the functions to edit http-level headers, I thought this would be a good way to emulate that.

**Comment by fruffy** [comment]
Do you think we can fully model REST with those RPCs? E.g., GET/POST/PUT/DELETE

**Comment by jessberg** [comment]
> Do you think we can fully model REST with those RPCs? E.g., GET/POST/PUT/DELETE

I think it would be pretty easy to put that information in the rpc;  as shown with this pull request, changing the fields of the rpc isn't too onerous or complex, so we could definitely put that information in the simulator.  However, right now the nodes don't actually do anything - they just pass along data without editing it.  So I don't think there would be any meaningful difference between a GET message and a POST one, or really any information that can be used besides the filter-defined headers.

**Review by fruffy — APPROVED** [review]
Hmm. Let's go with this for now. We can always untangle it later.

**Pull request merged**
