### PR TITLE
fixed issue where node names had preceding whitespace, and so equalit…

### PR DESCRIPTION
**Pull request by jessberg**
…y wasn't working.  Unfortunately the new group by stuff does not work unless I fix this bug, hence why a two line change is getting its own pull request.

### CODE REVIEW

**Comment by fruffy** [comment]
Why do the nodes have preceding whitespace in the first place? We should probably fix the issue at the source.

**Comment by jessberg** [comment]
> Why do the nodes have preceding whitespace in the first place? We should probably fix the issue at the source.

The nodes are gotten from splitting a string like "0, 1, 2".  I originally processed that string by splitting at commas, but because there are spaces between them, a space was also added.  This is the source - this is where we first use that path.

**Comment by fruffy** [comment]
I see, how is that string created?

**Comment by jessberg** [comment]
> I see, how is that string created?

Yes, it's added to a few lines before, at the beginning of the filter.  Then it is used to create the trace graph.

**Comment by fruffy** [comment]
Can't we just remove the whitespace there?

**Comment by jessberg** [comment]
Sure.  Let me edit the filter instead.

**Pull request closed without merging**
